development:
  adapter: postgresql
  encoding: unicode
  database: Mixr_development
  pool: 5
  host: localhost
  username: ericholland
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Mixr_test
  pool: 5
  host: localhost
  username: ericholland
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Mixr_production
  pool: 5
  host: localhost
  username: ericholland
  password:
